version: '3'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: Selenium_Server
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
  
  python:
    build: ./docker/python
    container_name: Selenium_Chrome_Python
    volumes: 
      - ./work:/work
    tty: true
    depends_on:
      - selenium
